<?xml version="1.0" encoding="utf-8" ?>
<!--
Generated by jade 
See john for source file
-->
<SMTK_AttributeManager Version="1">
  <Definitions>
    <AttDef Type="Material" Associations="f">
      <ItemDefinitions>
        <Double Name="Density">
          <RangeInfo>
            <Min Inclusive="false">0.0</Min>
          </RangeInfo>
        </Double>
        <Double Name="Viscosity">
          <RangeInfo>
            <Min Inclusive="false"></Min>
          </RangeInfo>
        </Double>
      </ItemDefinitions>
    </AttDef>
    <AttDef Type="BoundaryCondition" Associations="e"></AttDef>
    <AttDef Type="Velocity" BaseType="BoundaryCondition">
      <ItemDefinitions>
        <Double Name="Velocity" NumberOfRequiredValues="2"></Double>
      </ItemDefinitions>
    </AttDef>
    <AttDef Type="Pressure" BaseType="BoundaryCondition">
      <ItemDefinitions>
        <Double Name="Pressure"></Double>
      </ItemDefinitions>
    </AttDef>
  </Definitions>
</SMTK_AttributeManager>